-- ============================================================
-- Migration V2: Seed dữ liệu mặc định — Tài khoản Admin
-- Mô tả : Tạo tài khoản quản trị viên mặc định cho hệ thống.
--          Chỉ chạy một lần khi khởi tạo môi trường mới.
-- Lưu ý : ĐỔI MẬT KHẨU ngay sau khi triển khai lên production!
-- Thông tin đăng nhập mặc định:
--   Username : admin
--   Password : 123456  (hash bcrypt, cost=12)
-- ============================================================

-- Admin account is seeded at application startup by App.seedAdminIfNeeded(). See App.java.
